name: Format Check shfmt

on: [pull_request]

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install shfmt
        run: |
          sudo apt-get update
          sudo apt-get install -y shfmt

      - name: Run shfmt
        run: |
          shfmt -d -i 2 -ci .
