name: Run integration tests
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install tmux and neovim
        run: sudo apt-get update && sudo apt-get install -y tmux neovim

      - name: Run integration test
        run: bash tests/integration/run.sh

      - name: Run pick-nvim integration test
        run: bash tests/integration/pick_nvim.sh
