name: Run shellchec

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: shellcheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          severity: error
            
