name: Run Bats Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Bats and Bats libraries
        uses: bats-core/bats-action@2.0.0

      - name: Run Bats tests
        run: bats tests
            
